# open890 configuration
version = "1.0"

[ui.macros."40m CW"]
commands = [
  "FR0",
  "FA00007055000",
  "BS32",
  "BS43",
  "OM07",
  "FL00",
  "SL009",
  "SH0080"
]

[ui.macros."20m FT8"]
commands = [
  "FR0",            # VFO A
  "FA00014074000",  # VFO A freq
  "DE100",          # DELAY 1000ms
  "BS32",           # auto-scroll mode
  "BS40",           # bandscope span 5 khz
  "BSE",            # bandscope shift
  "BSK2",           # bandscope shift -2
  "OM02",           # USB
  "SL000",          # low cut 0 hz
  "SH0024",         # hi cut 3000 hz
  "FL00",           # FIL A
  "NR0",            # NR off
]

[ui.macros."80m Trivia"]
commands = [
  "FR0",            # VFO A
  "FA00003916000",  # VFO A freq
  "BS32",           # auto-scroll mode
  "BS43",           # bandscope span 50 khz
  "BSE",            # bandscope shift
  "BSK4",           # bandscope shift center
  "OM01",           # LSB
  "SL000",          # low cut 0 hz
  "SH0024",         # hi cut 3000 hz
  "FL00",           # FIL A
]

