name: Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3.4.6
          elixir-version: 1.10.4
          experimental-otp: true
      #- name: Retrieve Mix Dependencies Cache (uncompiled)
      #  uses: actions/cache@v2
      #  id: mix-cache # used to check if we can skip `mix deps.get`
      #  with:
      #    path: deps
      #    key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      #    restore-keys: |
      #      ${{ runner.os }}-mix-
      #- name: Retrieve Build Cache (compiled)
      #  uses: actions/cache@v2
      #  with:
      #    path: _build
      #    key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      #    restore-keys: |
      #      ${{ runner.os }}-build-
      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Compile
        run: |
          mix clean
          mix compile
        env:
          MIX_ENV: test
      - name: Credo
        run: |
          mix credo suggest --mute-exit-status
        env:
          MIX_ENV: test
      #  mix sobelow --ignore Config.CSP,Config.HTTPS
